### ISSUE TITLE
todo/ideas

### ISSUE THREAD

**Issue by jackdonofrio** [jackdonofrio/jerome#1]
- [ ] fix LXX passages with bad/missing numbering
- [ ] fix remaining few Psalms that are split 
- [x] make vocab tool menu properly scrollable
- [x] rewrite verse number extraction algorithm, there are some cases where it breaks
- [ ] update styling / positioning of query engine
- [ ] for scripture reader, add missing books

Long term
- [ ] build database of calendar readings to use instead of scraping
- [x]  add reader for entire Bible, other early Christian texts too (Didache, Ignatian epistles)
